version: '3'
services:
  cockroach:
    image: ubuntu:xenial-20170214
    command: /cockroach/cockroach start --insecure --listen-addr cockroach
    volumes:
      - ../../../../cockroach-linux-2.6.32-gnu-amd64:/cockroach/cockroach
  flyway:
    depends_on:
      - cockroach
    image: boxfuse/flyway:6.0.0-beta
    volumes:
      - ./sql:/sql
    command: migrate -user=root -url=jdbc:postgresql://cockroach:26257/defaultdb -locations=filesystem:/sql
